import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar/navbar";
import { getSessionServer } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { SideMenu } from "@/components/editor/side-menu";
import Sidemenu from "@/components/side-menu/sidemenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSessionServer();

    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider session={session}>
                    <div className="grid h-screen w-screen grid-cols-[200px_minmax(0, 1fr)]">
                        <Sidemenu />
                        <div className="bg-gray-200">
                            <Navbar />
                            {children}
                        </div>
                    </div>
                    <Toaster
                        theme="light"
                        position="top-center"
                        richColors={true}
                    />
                </SessionProvider>
            </body>
        </html>
    );
}
